1. It is now "snap" compatible\!. 2. Fixed removing new-lines from input and handling of error messages.

diff --git a/install b/install
--- a/install
+++ b/install
@@ -40,7 +40,7 @@ declare -A TYPE_ARGS
 
 #prints all the propsx_value_yyyy variables
 print_props_values() {
-    local msg=$(printf "Props1_Script: %s\tProps2_dependency: %s\tProps3_todo: %s\tProps4_upgrade: %s\n" "$props1_value_script" "$props2_value_dependency" "$props3_value_todo" "$props3_value_upgrade")
+    local msg=$(printf "Props1_Script: %s\tProps2_dependency: %s\tProps3_upgrade: %s\tProps4_snap: %s\n" "$props1_value_script" "$props2_value_dependency" "$props3_value_upgrade" "$props4_value_snap")
     log_msg --msg="$msg"
 }
 
@@ -51,12 +51,16 @@ print_props_values() {
 props1_value_script=
 props2_value_dependency=
 props3_value_upgrade=
+props4_value_snap=
+#starts from 1...4
+MAX_PROPS=4
 
 get_props_values() {
     #initialize
     props1_value_script=
     props2_value_dependency=
     props3_value_upgrade=
+    props4_value_snap=
 
     if [ -z "$1" ] && [ -z "$2" ]; then
 	log_msg -e --msg="get_props_value(): One of the two required arguments are empty."
@@ -72,6 +76,7 @@ get_props_values() {
 	    fi
 	    local props=
 	    local index=
+	    local column_count=0
 	    #count the number of words we obtained
 	    for index in "${!strict_line[@]}"; do
 		props="${strict_line[$index]}";
@@ -81,11 +86,14 @@ get_props_values() {
 		    props2_value_dependency="$props"
 		elif [ $index -eq 2 ]; then
 		    props3_value_upgrade="$props"
+		elif [ $index -eq 3 ]; then
+		    props4_value_snap="$props"
 		fi
+		((column_count+=1))
 	    done
 	    #we are supposed to get exactly 9 words, and anything beyond or lesser
 	    # than that indicates incorrect file format
-	    if [ "$index" -ne 2 ]; then
+	    if [ "$column_count" -ne "$MAX_PROPS" ]; then
 		log_msg -e --msg="get_props(): Error parsing line. Quitting." --line="$2"
 		exit 1		
 	    fi
@@ -109,6 +117,8 @@ column5_value_props=
 column6_value_lineno=
 column7_value_ppastatus=
 column8_value_installstatus=
+#starts from 1...8
+MAX_COLUMNS=8
 
 get_column_values() {
     #initialize
@@ -495,17 +505,37 @@ install_soft() {
 		if [ -n "$column7_value_ppastatus" ] && [ "$column7_value_ppastatus" -eq 1 ]; then
 		    #install the ppa to the repository
 		    msg=$(printf "Installing software \"%s\"..." "$soft")
-		    log_msg --msg="$msg" "$2"		    
-		    local retVal=0
+		    log_msg --msg="$msg" "$2"
+
+		    #we find out the type of install
+		    local retVal=1
 		    local result=
-		    #we also use --allow-unauthenticated
-		    result=$(sudo apt-get install -y --allow-unauthenticated "$soft" 2>&1)
-		    retVal=$?
+		    if [ "$props3_value_upgrade" -eq 1 ]; then
+			#we --allow-unauthenticated
+			result=$(sudo apt-get upgrade -y --allow-unauthenticated "$soft" 2>&1)
+			retVal=$?
+		    elif [ "$props4_value_snap" -eq 1 ]; then
+			#check if snap is installed
+			if ! type snap >> /dev/null 2>&1; then
+			    msg="$(printf "Snap seems to be not present. Please install it. Skipping current entry.")"
+			    result="$msg"
+			    retVal=1
+			else			    
+			    result=$(sudo snap install "$soft" 2>&1)
+			    retVal=$?
+			fi
+		    else
+			#we --allow-unauthenticated
+			result=$(sudo apt-get install -y --allow-unauthenticated "$soft" 2>&1)
+			retVal=$?
+		    fi
+
+		    #post installation processing
 		    if [ "$retVal" -eq 0 ]; then
 			#update the status
 			update_ppa_soft_array "$index" 8 1
 		    else
-			msg=$(printf "install_soft(): The following error occurred when trying to install software \"%s\": \n%s\n" "$soft" "$result")
+			msg=$(printf "Following error occurred when trying to install software \"%s\": \n%s\n" "$soft" "$result")
 			log_msg -e --msg="$msg" --line="$2"
 			#we are not storing the error message that was returned during the script call
 			update_ppa_soft_array "$index" 8 0
@@ -618,26 +648,29 @@ install_all_softs(){
 	    fi
 	done
     fi
-    
-    #refresh the repository for upgrades
-    log_msg --msg="Refreshing repository..."
-    #fix anything that may be broken
-    status=$(sudo dpkg --configure -a)
-    status=$(sudo apt-get update 2>&1)
-    #apt-get returns 100 on error and 0 on no error
-    #change the return value here as needed
-    if [ $? -eq 101 ]; then #$? -ne 0
-	msg=$(printf "Something went wrong when updating the repository. Status: %s" "$status")
-	log_msg -e --msg="$msg"
-	return 1
-    fi
-    
-    log_msg --msg="Installing any updates after refresh..."
-    #(sudo apt-get upgrade &> /dev/null)
-    if ! sudo apt-get -y upgrade &> /dev/null; then
-	msg=$(printf "Something went wrong when upgrading. Status: %s" "$status")
-	log_msg -e --msg="$msg"
-	return 1
+
+    #we only refresh if there was anything to be added
+    if [ "$ADD_FLG" -eq 1 ]; then
+	#refresh the repository for upgrades
+	log_msg --msg="Refreshing repository..."
+	#fix anything that may be broken
+	status=$(sudo dpkg --configure -a)
+	status=$(sudo apt-get update 2>&1)
+	#apt-get returns 100 on error and 0 on no error
+	#change the return value here as needed
+	if [ $? -eq 101 ]; then #$? -ne 0
+	    msg=$(printf "Something went wrong when updating the repository. Status: %s" "$status")
+	    log_msg -e --msg="$msg"
+	    return 1
+	fi
+	
+	log_msg --msg="Installing any updates after refresh..."
+	#(sudo apt-get upgrade &> /dev/null)
+	if ! sudo apt-get -y upgrade &> /dev/null; then
+	    msg=$(printf "Something went wrong when upgrading. Status: %s" "$status")
+	    log_msg -e --msg="$msg"
+	    return 1
+	fi
     fi
     
     #install the softwares
@@ -845,37 +878,8 @@ parse_args(){
 
     local parsed_args=$(getopt -o h -l list,install,add,help,type::,file: -n 'install-ppa' -- "$@" 2>&1)
 
-    #an ugly way of finding if the parsing of the arguments went through successfully
-    local line_count=$(echo "$parsed_args" | wc -l)
-    local index=1
-    #if we have more than 1 line then one must be the failure
-    if [ $line_count -gt 1 ] || [ -z "$parsed_args" ]; then
-	if [ $line_count -gt 1 ]; then
-	    while read line; do
-		if [ $index -eq 1 ]; then
-		    printf "%s\n" "$line"
-		    ((index+=1))
-		    break
-		fi
-	    done < <(echo "$parsed_args")
-	else
-	    printf "Invalid arguments received. Use -h or --help to see usage.\n"
-	fi
-	exit 0
-    fi
-    
-    #remove leading space(s).
-    local new_args=
-    index=1
-    for i in $parsed_args; do
-	if [ $index -eq 1 ]; then
-	    new_args=$i
-	    ((index+=1))
-	else
-	    new_args+=" $i"
-	fi
-    done
-
+    #remove any new-line chars
+    parsed_args="$(tr -d '\n' < <(echo "$parsed_args"))"
     parsed_args="$new_args"
     eval set -- $parsed_args
 
